<body style="font-family: Arial, sans-serif;">
    <div class="container"
        style="justify-content: center;align-items:center;text-align:center;width: 80%;margin-top: 5%;padding: 40px;border: 1px solid #CB6242;border-radius: 20px;background-color: transparent;color:#ffffff;">
        <div class="container"
            style="justify-content: center;align-items:center;text-align:center;padding: 20px;border: 1px solid #CB6242;background: #303030;border-radius:15px;box-shadow:6px 6px 12px #0d0d0d, -6px -6px 12px #353535">
            <a href="{{ env('APP_URL_DOMAIN') }}/login">

                <img style="width:50%;" {{--                     https://lh3.googleusercontent.com/fife/ALs6j_EadcpKnOJ7a_oVrb0Mnd927MUz4jw5AQ7h_oxkhKQzKL30nkf8wa5psae2Eag_pfyGEh1XlkXgdpbc_kuAywBTGdyHnRWz7zuCC8ggI3jRR8fSxSJYtijx-2jXzD9WpwVefOU7StDO-0fMEMDgWCDprbx-ZPd6FvQKOg9Up7hbz5geG09-OGwih4FXrshhrlqholFbG8WMIKACjMphKAn0ojMqfV0zDcHNqX0T85_NTJTmVutP53oAg9Ee6O7o05253ZHZ_D1CMh8d9CX5rMh5Qbd9a4uijQwtLRdUF-fizJma2PwQMYrH0H1Vf05A_wpv0JuCA6xv2nimRZ6apu5NWN9WNbuNzjRe0IT8v0lfMabE4weBRmZkEQW3VO_U6-mDOQCGwwQIm-0JqS4bxhScoNXn0TRNw4UnUMPPZjtsZSQ6E_gTtejJg_wSkt9kbHNaQdi_sCQMUloGqioCHsk4ZepLDRPdlRkESsQ9-HEoMCGBpWOMRQxLyzV3YccP4qrYSIdMihzZB0YjgcRmcSz4sl5oWy2BCuOpPgW73Ya0O6NxTXe0vv6L9VLmNQsokBJPZh6LGGg6xZ1jyB1M4-OIRsKMSnvR28JmlXBwoUdIGZLbisGuzE7OQGpbKcBPGUksspOxdGdIGaNM6E9WLAq9wAwLG9eHX1LAe1w3bLIU2KfRu0ag04QxvwWNVAto2Onu0zkLm3_5a8DJgQtVQX_VTAtCdcVmBSYCQZpmrH0-IuRk7-HKY8iN_aPP1C9UuaS8mKhl8haCxs6oW6T3R879A29-Vr3ZAtv3SXD3bTad5XFwSFf3U3NLt2x4QZkXMuO1Kplg3iR7BTBnAdOWcolL4lwWku0dzuSfxJfLInzBqxUc1exOe9IzS3k5FQ9DUD5DrUSbFcUR-pGRIuGuvyCW-qyjWSa0WSDTMSD1C6wq4p0YDl2ycE2r7fES7q8lLsRXK8XEeN4yz8x0dFsaT3PnP_uTcu8en3-rulMlAT85095IW4DR3hdM4xpjPeaeKYU0RWwBVp3Jn4QFBgBhvTiXUEI03P80vseuSINz-GMyQSC_t86imanfNo5ZpiaOPRYNtCNL86qR0nUZQWlstTomak7suIOPQCKilZv5BBed1szCSX84QRhXzhsBwOOLyj3z34SD_W8sbFqvt-JtPp_bAydw6Z8KkoIQa_fjoWza39c3WVONBgKtGpkYxJz6IhZe2RBZeAewmUZXATVXJSIJfR3UFz_GUvV2138kptQiEK6--THcn10RG49Acmpm8VVH9_CCrcziGzn-hW21go24TxBDT7QVfDhUSQNkvoJuBzoMtFL-oUZLTZxZesd9zkRtLG5F4W-PYUsiPGcQbECH2EeCQ3upwnRhbN7F3LMOrq3bQdHcVtWNfr0oosUzJn-_YU9jubJWHpM_lCR5F3olKHG34W7Pd8EUTfZqjZpYGR6kTEtZIx1SxSn406CfWMwuWpT6MxWbMe9UsSmuZdxZ6sfVnMB3WgtdrbXgoGU-RrpRUtf8lsmbh8b4jTruQlCwo9Exv7A=w2000-h1252 --}} src="https://badion.w3spaces.com/badion.png" alt="Logo">
            </a>
            <h1 style="color: #CB6242;">Hey</h1>
            <h1 style="color: #CB6242;">Hi {{ $mailData['name'] }} Welcome To BadiOn</h1>
            <h3 style="color: #CB6242;">Your OTP is <label style="color:white">{{ $mailData['otp'] }}</label></h3>
            <code style="color: #CB6242;">Note:- This is an Autogenerated OTP, Do not share with anyone</code>
        </div>
    </div>
</body>
